# Generated by Django 3.0.7 on 2020-12-15 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('United', '0003_event_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('comment_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='United.Event')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
