# Generated by Django 3.1.7 on 2021-03-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('United', '0008_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='web_url',
            field=models.URLField(null=True),
        ),
    ]
